# Generated by Django 2.2.7 on 2020-01-22 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20191229_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='_price',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=19),
        ),
        migrations.AddField(
            model_name='product',
            name='measurement',
            field=models.CharField(blank=True, help_text='e.g Tonnes:Tonne:T', max_length=255, null=True),
        ),
    ]
