# Generated by Django 2.2.7 on 2020-02-23 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20200122_1605'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='price',
            new_name='_price',
        ),
    ]
